Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05fa00d4c63e32376
      Tags:
        - Key: Name
          Value: !Join [ " ", [ This, is, My, Instance]]



